# System HASS Module
#
# Provides local system monitoring and info.

sensor:

  - platform: command_line
    name: CPU Temp
    command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "ÂºC"
    value_template: '{{ value | multiply(0.001) }}'

  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot
    #- type: network_in
    #  arg: eth0
    #- type: network_out
    #  arg: eth0

