# Presence HASS Module
#
# Scripts and automations for "leaving home" event


automation:
- alias: Notify Arrival Home
  trigger:
    platform: state
    entity_id: device_tracker.jmobile
    from: 'not_home'
    to: 'home'
  action:
    - service: script.welcome_procedure


script:

  welcome_music:
    # Play music if welcome music is enabled
    sequence:
      - condition: state
        entity_id: input_boolean.welcome_music
        state: 'on'

      - service: media_player.volume_set
        entity_id:
          - media_player.clementine_remote
        data_template:
          volume_level: "{{ states.input_slider.profile_volume.state }}"
      - service: media_player.media_play
        entity_id:
          - media_player.clementine_remote

  welcome_report:
    # Play report if welcome report is enabled
    sequence:
      - condition: state
        entity_id: input_boolean.welcome_report
        state: 'on'

      - service: script.home_report
        data_template:
          notify_mobile: False

  welcome_procedure:
    sequence:

      - service: script.welcome_music

      - delay: 0:05

      - service: script.notify
        data_template:
          notify_text: "Hola Jota Â¡bienvenido a casa!"
          notify_mobile: False

      - delay: 00:00:08

      - service: script.welcome_report

